import yfinance as yf
from strategies.features import add_all_features
from data.labeling import add_target
from models.training import train_and_evaluate
from utils.logger import setup_logger

logger = setup_logger("Main_Phase2")

def main():
    logger.info("Starting Phase 2: Feature Engineering & Model Training")
    
    # 1. Fetch Data (Extended period for better training)
    ticker = "THYAO.IS"
    logger.info(f"Fetching 2 years of data for {ticker}...")
    df = yf.download(ticker, period="2y", interval="1d", auto_adjust=False, progress=False)

    # Flatten yfinance MultiIndex if present
    if hasattr(df.columns, 'nlevels') and df.columns.nlevels > 1:
        df.columns = df.columns.droplevel(1)
        
    logger.info(f"Raw Data Shape: {df.shape}")
    
    # 2. Add Features
    logger.info("Adding Technical Features (RSI, MACD, SMA)...")
    df_features = add_all_features(df)
    
    # Drop NaNs generated by rolling windows (e.g. SMA_200 needs 200 days)
    df_features = df_features.dropna()
    logger.info(f"Data Shape after Features & DropNaN: {df_features.shape}")
    
    # 3. Add Target
    logger.info("Adding Label (Target)...")
    df_labeled = add_target(df_features)
    logger.info(f"Data Shape after Labeling: {df_labeled.shape}")

    # 4. Define Feature Columns (Input for the Brain)
    features = ['RSI', 'SMA_50', 'SMA_200', 'macd', 'macd_signal', 'macd_hist', 'ATR']
    
    # 5. Train & Evaluate
    logger.info("Training Random Forest Loop...")
    model, precision, preds = train_and_evaluate(df_labeled, features)
    
    # 6. Basic Result Interpretation
    target_dist = df_labeled['Target'].value_counts(normalize=True)
    logger.info(f"Baseline (Buy/Hold) Probability: {target_dist.get(1, 0):.2f}")
    
    if precision > target_dist.get(1, 0):
        logger.info("✅ Model is better than random guessing!")
    else:
        logger.warning("⚠️ Model needs improvement (underperforming baseline).")

if __name__ == "__main__":
    main()
